#!/usr/bin/env node

/**
 * Generates NOTICE file dynamically from SKILL.md frontmatter source fields
 * and README credits section.
 *
 * Usage: node scripts/generate-notice.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SKILLS_DIR = path.join(ROOT, ".claude", "skills");

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const fm = {};
  const lines = match[1].split("\n");
  let currentKey = null;
  for (const line of lines) {
    if (currentKey && /^\s+\S/.test(line)) {
      const cont = line.trim();
      if (fm[currentKey] && fm[currentKey] !== ">" && fm[currentKey] !== "|") {
        fm[currentKey] += " " + cont;
      } else {
        fm[currentKey] = cont;
      }
      continue;
    }
    const idx = line.indexOf(":");
    if (idx === -1) { currentKey = null; continue; }
    const key = line.slice(0, idx).trim();
    const val = line.slice(idx + 1).trim();
    if (!key) { currentKey = null; continue; }
    currentKey = key;
    fm[key] = val === ">" || val === "|" ? val : val;
  }
  for (const key of Object.keys(fm)) {
    if (fm[key] === ">" || fm[key] === "|") fm[key] = "";
    // Strip quotes
    if (typeof fm[key] === "string") fm[key] = fm[key].replace(/^["']|["']$/g, "");
  }
  return fm;
}

function scanSkillSources() {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  const results = [];

  for (const entry of fs.readdirSync(SKILLS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillFile = path.join(SKILLS_DIR, entry.name, "SKILL.md");
    if (!fs.existsSync(skillFile)) continue;

    const content = fs.readFileSync(skillFile, "utf-8");
    const fm = parseFrontmatter(content);

    if (fm.source || fm.author) {
      results.push({
        name: fm.name || entry.name,
        source: fm.source || null,
        author: fm.author || null,
      });
    }
  }

  return results.sort((a, b) => a.name.localeCompare(b.name));
}

// Known external sources (skills without source in frontmatter)
const KNOWN_SOURCES = {
  "frontend-design": { source: "https://github.com/anthropics/skills", author: "Anthropic" },
  "webapp-testing": { source: "https://github.com/anthropics/skills", author: "Anthropic" },
  "trailofbits-security": { source: "https://github.com/trailofbits/skills", author: "Trail of Bits" },
  "web-quality": { source: "https://github.com/addyosmani/web-quality-skills", author: "Addy Osmani" },
  "stripe-best-practices": { source: "https://github.com/stripe/ai", author: "Stripe" },
  "terraform": { source: "https://github.com/hashicorp/agent-skills", author: "HashiCorp" },
  "firecrawl-cli": { source: "https://github.com/firecrawl/cli", author: "Firecrawl" },
  "composition-patterns": { source: "https://github.com/vercel-labs/agent-skills", author: "Vercel" },
  "better-auth": { source: "https://github.com/better-auth/skills", author: "Better Auth" },
  "planning-with-files": { source: "https://github.com/OthmanAdi/planning-with-files", author: "OthmanAdi" },
  "obsidian-skills": { source: "https://github.com/kepano/obsidian-skills", author: "Kepano (Obsidian)" },
  "claude-seo": { source: "https://github.com/AgriciDaniel/claude-seo", author: "AgriciDaniel" },
  "notebooklm-skill": { source: "https://github.com/PleasePrompto/notebooklm-skill", author: "PleasePrompto" },
};

function generateNotice() {
  const skills = scanSkillSources();
  const year = new Date().getFullYear();

  // Merge known sources with frontmatter sources
  const allSkills = new Map();
  for (const skill of skills) {
    allSkills.set(skill.name, skill);
  }
  for (const [name, info] of Object.entries(KNOWN_SOURCES)) {
    if (!allSkills.has(name)) {
      allSkills.set(name, { name, ...info });
    } else {
      const existing = allSkills.get(name);
      if (!existing.source) existing.source = info.source;
      if (!existing.author) existing.author = info.author;
    }
  }

  // Group by author/source
  const byAuthor = {};
  for (const [, skill] of allSkills) {
    const key = skill.author || "Community";
    if (!byAuthor[key]) byAuthor[key] = [];
    byAuthor[key].push(skill);
  }

  // Build NOTICE content
  let notice = `Claude Skills Vault
Copyright ${year} George Khananaev

This project is licensed under the MIT License - see the LICENSE file for details.

ATTRIBUTION
-----------
When using or redistributing this project, please provide attribution by:

1. Keeping the LICENSE file intact in any copies or substantial portions
2. Including a link to the original repository:
   https://github.com/georgekhananaev/claude-skills-vault

THIRD-PARTY CREDITS
-------------------
Skills in this vault are sourced from multiple authors and organizations.
This file is auto-generated by: node scripts/generate-notice.js

`;

  // George's own skills (no source field, no known source)
  const georgeSkills = [];
  for (const entry of fs.readdirSync(SKILLS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (!allSkills.has(entry.name)) {
      georgeSkills.push(entry.name);
    } else {
      const s = allSkills.get(entry.name);
      if (s.author === "George Khananaev") georgeSkills.push(entry.name);
    }
  }

  if (georgeSkills.length > 0) {
    notice += `George Khananaev (maintainer):\n`;
    for (const name of georgeSkills.sort()) {
      notice += `  - ${name}\n`;
    }
    notice += `\n`;
  }

  // External authors
  const sortedAuthors = Object.keys(byAuthor).sort();
  for (const author of sortedAuthors) {
    if (author === "George Khananaev") continue;
    const skills = byAuthor[author];
    const source = skills[0].source || "";
    notice += `${author}${source ? " (" + source + ")" : ""}:\n`;
    for (const skill of skills.sort((a, b) => a.name.localeCompare(b.name))) {
      notice += `  - ${skill.name}\n`;
    }
    notice += `\n`;
  }

  // PR contributors
  notice += `COMMUNITY CONTRIBUTORS (Pull Requests)
--------------------------------------
garesuta (https://github.com/garesuta) — PR #4, #5:
  - react-best-practices, next-cache-components, next-upgrade, senior-backend
  - multi-agent-patterns, parallel-agents, vercel-react-native-skills

palakorn-moonholidays (https://github.com/palakorn-moonholidays) — PR #6:
  - owasp-security, color-accessibility-audit

ComposioHQ (https://github.com/ComposioHQ):
  - document-skills (docx, pdf, pptx, xlsx), project-change-log, skill-creator, mcp-builder
`;

  return notice;
}

const notice = generateNotice();
const outPath = path.join(ROOT, "NOTICE");
fs.writeFileSync(outPath, notice);
console.log(`NOTICE generated (${notice.split("\n").length} lines)`);
